### ISSUE TITLE
多个bean需要回调销毁方法,在for循环remove

### ISSUE THREAD

**Issue by NotGiveUp** [DerekYRC/mini-spring#31]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/33014847/185521049-2ab8bc5b-2fed-4e67-a291-dc363afc0129.png">

**Comment by DerekYRC** [comment]
@NotGiveUp 问题是？

**Comment by NotGiveUp** [comment]
在for循环里 remove报错 java.util.ConcurrentModificationException

**Comment by DerekYRC** [comment]
@NotGiveUp  很奇怪，这么写理论上没有问题，日志能贴一下吗

**Comment by NotGiveUp** [comment]
你搞2个bean 实现DisposableBean 跑你的test 就行;


java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:76)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:190)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:186)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:168)
	at org.springframework.test.ioc.CircularReferenceWithProxyBeanTest.testCircularReference(CircularReferenceWithProxyBeanTest.java:23)

**Comment by DerekYRC** [comment]
@NotGiveUp get，beanNames指向disposableBeans.keySet()。有兴趣可以参考spring的做法提个pull request。
![image](https://user-images.githubusercontent.com/44155264/186084733-a368f844-1274-48ae-9e72-14931da73aad.png)

**Comment by DerekYRC** [comment]
今晚修复下
